#!/usr/bin/env node
/**
 * @tpvpn/tokens — build pipeline
 *
 * Reads the W3C DTCG token source in ./src (primitives → semantic → component),
 * resolves references with Style Dictionary v4 and emits every platform output
 * into ./dist:
 *
 *   dist/css/tokens.css            :root { --tp-<path>: value }        (every token)
 *   dist/tailwind/theme.css        Tailwind v4 @theme + :root extras
 *   dist/json/tokens.json          nested tree, references resolved
 *   dist/json/tokens.flat.json     { "color.bg.canvas": { value, type, description, original } }
 *   dist/dart/tp_tokens.dart       abstract final class TpTokens (Flutter)
 *   dist/swift/TPTokens.swift      public enum TPTokens (UIKit)
 *   dist/kotlin/TpTokens.kt        object TpTokens (Jetpack Compose)
 *   dist/android/values/colors.xml + dimens.xml
 *   dist/figma/tokens.json         Tokens Studio single-file format (references kept)
 *   dist/README.md                 consumption guide
 *
 * Usage: node build.mjs
 */

import StyleDictionary from 'style-dictionary';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(ROOT, 'dist');
const HEADER = 'Generated by @tpvpn/tokens — do not edit';

const SOURCE = [
  'src/primitives/color.json',
  'src/primitives/dimension.json',
  'src/primitives/motion.json',
  'src/primitives/typography.json',
  'src/semantic/color.json',
  'src/semantic/elevation.json',
  'src/semantic/typography.json',
  'src/component/components.json',
].map((p) => path.join(ROOT, p));

const COMPONENT_GROUPS = [
  'button',
  'connection-button',
  'node-card',
  'tag',
  'tab-bar',
  'switch',
  'input',
  'search-bar',
  'country-list-item',
];

/* ────────────────────────────────────────────────────────────────────────── */
/* Generic helpers                                                            */
/* ────────────────────────────────────────────────────────────────────────── */

/** Number → shortest decimal string with at most `d` decimals (no trailing zeros). */
function fmt(n, d = 4) {
  if (!Number.isFinite(n)) throw new Error(`fmt(): non-finite number ${n}`);
  const s = n.toFixed(d);
  return s.includes('.') ? s.replace(/\.?0+$/, '') : s;
}

/** Number → decimal literal that always contains a '.', for Dart/Swift/Kotlin doubles. */
function dbl(n, d = 4) {
  const s = fmt(n, d);
  return s.includes('.') ? s : `${s}.0`;
}

/** "12px" | "-0.02em" | 12 → { n, u } */
function parseUnit(v) {
  if (typeof v === 'number') return { n: v, u: '' };
  const m = String(v).trim().match(/^(-?\d*\.?\d+)([a-z%]*)$/i);
  if (!m) throw new Error(`parseUnit(): cannot parse "${v}"`);
  return { n: parseFloat(m[1]), u: m[2] };
}

/** "12px" → 12 (throws if the unit is not px / unitless) */
function px(v) {
  const { n, u } = parseUnit(v);
  if (u !== 'px' && u !== '') throw new Error(`px(): expected px, got "${v}"`);
  return n;
}

/** "200ms" | "1.2s" → milliseconds (number) */
function ms(v) {
  const { n, u } = parseUnit(v);
  if (u === 's') return n * 1000;
  if (u === 'ms' || u === '') return n;
  throw new Error(`ms(): expected ms/s, got "${v}"`);
}

/** px → rem string (base 16), up to 4 decimals */
function rem(pxValue) {
  return `${fmt(pxValue / 16)}rem`;
}

/**
 * Parse a CSS colour into { r, g, b, a } (0–255 ints, a 0–1 float).
 * Supports #RGB, #RRGGBB, #RRGGBBAA, rgb()/rgba() (comma syntax) and "transparent".
 */
function parseColor(v) {
  const s = String(v).trim();
  if (s === 'transparent') return { r: 0, g: 0, b: 0, a: 0 };
  let m = s.match(/^#([0-9a-f]{3,8})$/i);
  if (m) {
    let h = m[1];
    if (h.length === 3 || h.length === 4) h = [...h].map((c) => c + c).join('');
    const r = parseInt(h.slice(0, 2), 16);
    const g = parseInt(h.slice(2, 4), 16);
    const b = parseInt(h.slice(4, 6), 16);
    const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
    return { r, g, b, a };
  }
  m = s.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*(\d*\.?\d+)\s*)?\)$/i);
  if (m) {
    return { r: +m[1], g: +m[2], b: +m[3], a: m[4] === undefined ? 1 : parseFloat(m[4]) };
  }
  throw new Error(`parseColor(): cannot parse "${v}"`);
}

const hex2 = (n) => Math.round(n).toString(16).padStart(2, '0').toUpperCase();
const argbHex = ({ r, g, b, a }) => `${hex2(a * 255)}${hex2(r)}${hex2(g)}${hex2(b)}`;

/** Normalise a CSS colour string for output (hex upper-case, rgba spacing tidy). */
function cssColor(v) {
  const s = String(v).trim();
  if (s === 'transparent') return s;
  if (s.startsWith('#')) return s.toUpperCase();
  const c = parseColor(s);
  return c.a === 1 ? `rgb(${c.r}, ${c.g}, ${c.b})` : `rgba(${c.r}, ${c.g}, ${c.b}, ${fmt(c.a, 3)})`;
}

/** ["Inter", "SF Pro Text", "sans-serif"] → Inter, 'SF Pro Text', sans-serif */
function cssFontFamily(list) {
  const arr = Array.isArray(list) ? list : [list];
  return arr.map((f) => (/[^a-z0-9_-]/i.test(f) ? `'${f}'` : f)).join(', ');
}

/** [a, b, c, d] → cubic-bezier(a, b, c, d) */
function cssBezier(arr) {
  return `cubic-bezier(${arr.map((n) => fmt(n)).join(', ')})`;
}

/** A single px length for shadow strings: "0px" → "0", "12px" → "12px" */
function shadowLen(v) {
  const n = px(v);
  return n === 0 ? '0' : `${fmt(n)}px`;
}

/** DTCG shadow (object | array | []) → CSS box-shadow value */
function cssShadow(value) {
  const layers = Array.isArray(value) ? value : [value];
  if (layers.length === 0) return 'none';
  return layers
    .map((l) => {
      const parts = [];
      if (l.inset) parts.push('inset');
      parts.push(shadowLen(l.offsetX), shadowLen(l.offsetY), shadowLen(l.blur));
      if (px(l.spread ?? '0px') !== 0) parts.push(shadowLen(l.spread));
      parts.push(cssColor(l.color));
      return parts.join(' ');
    })
    .join(', ');
}

/** Typography composite → ordered [suffix, cssValue] pairs */
function typographyParts(t) {
  const out = [
    ['font-family', cssFontFamily(t.fontFamily)],
    ['font-size', String(t.fontSize)],
    ['line-height', String(t.lineHeight)],
    ['font-weight', String(t.fontWeight)],
    ['letter-spacing', String(t.letterSpacing)],
  ];
  if (t.textTransform) out.push(['text-transform', String(t.textTransform)]);
  if (t.fontVariantNumeric) out.push(['font-variant-numeric', String(t.fontVariantNumeric)]);
  return out;
}

/** Scalar (non-typography) token → CSS value string */
function cssValue(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':
      return cssColor(v);
    case 'shadow':
      return cssShadow(v);
    case 'cubicBezier':
      return cssBezier(v);
    case 'fontFamily':
      return cssFontFamily(v);
    case 'dimension':
    case 'duration':
    case 'string':
      return String(v);
    case 'fontWeight':
    case 'number':
      return String(v);
    default:
      throw new Error(`cssValue(): unhandled $type "${token.$type}" at ${token.path.join('.')}`);
  }
}

/**
 * Token → [[cssVarName, value], ...] with `prefix` (e.g. "--tp-").
 * Typography composites expand into several variables.
 */
function cssDeclarations(token, prefix) {
  const base = prefix + kebab(token.path);
  if (token.$type === 'typography') {
    return typographyParts(token.$value).map(([suffix, val]) => [`${base}-${suffix}`, val]);
  }
  return [[base, cssValue(token)]];
}

/* naming ------------------------------------------------------------------ */

const kebab = (p) => p.join('-');
const snake = (p) => p.join('_').replace(/-/g, '_');
function camel(p) {
  const words = p.join('-').split('-').filter(Boolean);
  return words
    .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');
}
function pascal(p) {
  const c = camel(p);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

const isGroup = (token, ...groups) => groups.includes(token.path[0]);
const isComponent = (token) => isGroup(token, ...COMPONENT_GROUPS);
const displayPath = (token) => token.path.join('.');

/** Group tokens by their first path segment, preserving order. */
function sectionsOf(tokens) {
  const map = new Map();
  for (const t of tokens) {
    const key = t.path[0];
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(t);
  }
  return map;
}

const dq = (s) => `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const sq = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/* ────────────────────────────────────────────────────────────────────────── */
/* 1. dist/css/tokens.css                                                     */
/* ────────────────────────────────────────────────────────────────────────── */

function formatCss({ dictionary }) {
  const lines = [`/* ${HEADER} */`, '', ':root {'];
  for (const [group, tokens] of sectionsOf(dictionary.allTokens)) {
    lines.push(`  /* ${group} */`);
    for (const t of tokens) {
      for (const [name, value] of cssDeclarations(t, '--tp-')) lines.push(`  ${name}: ${value};`);
    }
    lines.push('');
  }
  if (lines.at(-1) === '') lines.pop();
  lines.push('}', '');
  return lines.join('\n');
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 2. dist/tailwind/theme.css                                                 */
/* ────────────────────────────────────────────────────────────────────────── */

function formatTailwind({ dictionary }) {
  const all = dictionary.allTokens;
  const by = (pred) => all.filter(pred);
  const theme = [];
  const root = [];
  const section = (arr, title) => arr.push('', `  /* ${title} */`);

  // Colours — primitives + semantics share the "color" root; drop the leading segment.
  section(theme, 'Colours — primitives');
  for (const t of by((t) => t.path[0] === 'color' && !SEMANTIC_COLOR_GROUPS.has(t.path[1]))) {
    theme.push(`  --color-${kebab(t.path.slice(1))}: ${cssColor(t.$value)};`);
  }
  section(theme, 'Colours — semantic');
  for (const t of by((t) => t.path[0] === 'color' && SEMANTIC_COLOR_GROUPS.has(t.path[1]))) {
    theme.push(`  --color-${kebab(t.path.slice(1))}: ${cssColor(t.$value)};`);
  }

  // Typography roles
  section(theme, 'Typography roles (text-<role>)');
  for (const t of by((t) => t.$type === 'typography' && t.path[0] === 'typography')) {
    const role = kebab(t.path.slice(1));
    const v = t.$value;
    const notes = [];
    if (v.textTransform) notes.push(`text-transform: ${v.textTransform}`);
    if (v.fontVariantNumeric) notes.push(`font-variant-numeric: ${v.fontVariantNumeric}`);
    if (notes.length) theme.push(`  /* ${role}: ${notes.join('; ')} */`);
    theme.push(`  --text-${role}: ${rem(px(v.fontSize))};`);
    theme.push(`  --text-${role}--line-height: ${rem(px(v.lineHeight))};`);
    theme.push(`  --text-${role}--font-weight: ${v.fontWeight};`);
    theme.push(`  --text-${role}--letter-spacing: ${v.letterSpacing};`);
  }

  // Font families / weights / tracking
  section(theme, 'Font families');
  for (const t of by((t) => t.path[0] === 'font' && t.path[1] === 'family')) {
    theme.push(`  --font-${kebab(t.path.slice(2))}: ${cssFontFamily(t.$value)};`);
  }
  section(theme, 'Font weights');
  for (const t of by((t) => t.path[0] === 'font' && t.path[1] === 'weight')) {
    theme.push(`  --font-weight-${kebab(t.path.slice(2))}: ${t.$value};`);
  }
  section(theme, 'Letter spacing');
  for (const t of by((t) => t.path[0] === 'font' && t.path[1] === 'letter-spacing')) {
    theme.push(`  --tracking-${kebab(t.path.slice(2))}: ${t.$value};`);
  }

  // Radius
  section(theme, 'Radius');
  for (const t of by((t) => t.path[0] === 'radius')) {
    theme.push(`  --radius-${kebab(t.path.slice(1))}: ${t.$value};`);
  }

  // Shadows
  section(theme, 'Elevation');
  for (const t of by((t) => t.path[0] === 'elevation')) {
    const layers = Array.isArray(t.$value) ? t.$value : [t.$value];
    const inset = layers.length > 0 && layers.every((l) => l.inset);
    const name = inset
      ? `--inset-shadow-${kebab(t.path.slice(1)).replace(/^inset-/, '')}`
      : `--shadow-${kebab(t.path.slice(1))}`;
    theme.push(`  ${name}: ${cssShadow(t.$value)};`);
  }

  // Motion
  section(theme, 'Motion');
  for (const t of by((t) => t.path[0] === 'easing')) {
    theme.push(`  --ease-${kebab(t.path.slice(1))}: ${cssBezier(t.$value)};`);
  }
  for (const t of by((t) => t.path[0] === 'duration')) {
    theme.push(`  --duration-${kebab(t.path.slice(1))}: ${t.$value};`);
  }

  // Layout
  section(theme, 'Breakpoints & containers');
  for (const t of by((t) => t.path[0] === 'breakpoint')) {
    theme.push(`  --breakpoint-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  for (const t of by((t) => t.path[0] === 'container')) {
    theme.push(`  --container-${kebab(t.path.slice(1))}: ${t.$value};`);
  }

  // Spacing scale + named sizes (spacing namespace → h-*, w-*, size-*, p-*, gap-* …)
  section(theme, 'Spacing (4pt grid) & named sizes');
  theme.push('  --spacing: 0.25rem;');
  for (const t of by((t) => t.path[0] === 'size' && t.path[1] !== 'logo')) {
    const rest = t.path.slice(1).map((s) => (s === 'connection-button' ? 'connection' : s));
    theme.push(`  --spacing-${kebab(rest)}: ${t.$value};`);
  }

  // :root extras — non-namespaced tokens and component tokens
  section(root, 'Gradients');
  for (const t of by((t) => t.path[0] === 'gradient')) {
    root.push(`  --gradient-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  section(root, 'Z-index');
  for (const t of by((t) => t.path[0] === 'z-index')) {
    root.push(`  --z-index-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  section(root, 'Opacity');
  for (const t of by((t) => t.path[0] === 'opacity')) {
    root.push(`  --opacity-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  section(root, 'Logo ratios & minimum sizes');
  for (const t of by((t) => t.path[0] === 'logo')) {
    root.push(`  --logo-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  for (const t of by((t) => t.path[0] === 'size' && t.path[1] === 'logo')) {
    root.push(`  --logo-${kebab(t.path.slice(2))}: ${t.$value};`);
  }
  section(root, 'Border widths');
  for (const t of by((t) => t.path[0] === 'border-width')) {
    root.push(`  --border-width-${kebab(t.path.slice(1))}: ${t.$value};`);
  }
  section(root, 'Component tokens (resolved)');
  for (const t of by(isComponent)) {
    for (const [name, value] of cssDeclarations(t, '--tp-')) root.push(`  ${name}: ${value};`);
  }

  return [
    `/* ${HEADER} */`,
    '/* Tailwind CSS v4 theme for TP VPN. Light mode only. */',
    '',
    '@theme {',
    ...theme.slice(1),
    '}',
    '',
    ':root {',
    ...root.slice(1),
    '}',
    '',
  ].join('\n');
}

const SEMANTIC_COLOR_GROUPS = new Set([
  'bg',
  'fg',
  'border',
  'action',
  'status',
  'state',
  'latency',
  'scene',
  'chart',
  'ring',
]);

/* ────────────────────────────────────────────────────────────────────────── */
/* 3. dist/json/tokens.json + tokens.flat.json                                */
/* ────────────────────────────────────────────────────────────────────────── */

function formatJsonNested({ dictionary }) {
  const tree = {};
  for (const t of dictionary.allTokens) {
    let node = tree;
    for (const seg of t.path.slice(0, -1)) {
      node[seg] ??= {};
      node = node[seg];
    }
    const leaf = { $value: t.$value, $type: t.$type };
    if (t.$description) leaf.$description = t.$description;
    node[t.path.at(-1)] = leaf;
  }
  return JSON.stringify(tree, null, 2) + '\n';
}

function formatJsonFlat({ dictionary }) {
  const flat = {};
  for (const t of dictionary.allTokens) {
    const entry = { value: t.$value, type: t.$type };
    if (t.$description) entry.description = t.$description;
    entry.original = t.original.$value;
    flat[displayPath(t)] = entry;
  }
  return JSON.stringify(flat, null, 2) + '\n';
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 4. dist/dart/tp_tokens.dart                                                */
/* ────────────────────────────────────────────────────────────────────────── */

function dartColor(v) {
  const s = String(v).trim();
  if (s === 'transparent') return 'Color(0x00000000)';
  const c = parseColor(s);
  if (s.startsWith('#')) return `Color(0x${argbHex(c)})`;
  return `Color.fromRGBO(${c.r}, ${c.g}, ${c.b}, ${dbl(c.a, 3)})`;
}

function dartShadowLayer(l) {
  const c = parseColor(l.color);
  const args = [
    `color: Color(0x${argbHex(c)})`,
    `offset: Offset(${fmt(px(l.offsetX))}, ${fmt(px(l.offsetY))})`,
    `blurRadius: ${fmt(px(l.blur))}`,
  ];
  const spread = px(l.spread ?? '0px');
  if (spread !== 0) args.push(`spreadRadius: ${fmt(spread)}`);
  return `BoxShadow(${args.join(', ')})`;
}

const DART_WEIGHT = (w) => `FontWeight.w${w}`;

function formatDart({ dictionary }) {
  const out = [
    `// ${HEADER}`,
    '',
    "import 'package:flutter/material.dart';",
    '',
    '/// TP VPN design tokens (Light mode only).',
    '///',
    '/// Naming: token path `color.bg.canvas` → `TpTokens.colorBgCanvas`.',
    '/// Typography roles are `TextStyle` constants (fontSize, height, fontWeight,',
    '/// letterSpacing in logical px, tabular figures where the role requires it).',
    '/// Pair them with `fontFamily: TpTokens.fontFamilySans.first`.',
    'abstract final class TpTokens {',
  ];
  let first = true;
  for (const [group, tokens] of sectionsOf(dictionary.allTokens)) {
    if (!first) out.push('');
    first = false;
    out.push(`  // ── ${group} ${'─'.repeat(Math.max(2, 60 - group.length))}`);
    for (const t of tokens) {
      const name = camel(t.path);
      const doc = t.$description ? `  /// ${t.$description}\n` : '';
      const v = t.$value;
      switch (t.$type) {
        case 'color':
          out.push(`${doc}  static const Color ${name} = ${dartColor(v)};`);
          break;
        case 'dimension': {
          const { n, u } = parseUnit(v);
          if (u === 'em') {
            out.push(`${doc}  /// Unit: em (multiply by the font size).\n  static const double ${name} = ${dbl(n)};`);
          } else {
            out.push(`${doc}  static const double ${name} = ${fmt(n)};`);
          }
          break;
        }
        case 'number': {
          const isInt = Number.isInteger(v) && isGroup(t, 'z-index', 'grid');
          out.push(`${doc}  static const ${isInt ? 'int' : 'double'} ${name} = ${isInt ? v : dbl(v)};`);
          break;
        }
        case 'fontWeight':
          out.push(`${doc}  static const FontWeight ${name} = ${DART_WEIGHT(v)};`);
          break;
        case 'fontFamily':
          out.push(`${doc}  static const List<String> ${name} = [${v.map(sq).join(', ')}];`);
          break;
        case 'duration':
          out.push(`${doc}  static const Duration ${name} = Duration(milliseconds: ${fmt(ms(v))});`);
          break;
        case 'cubicBezier':
          out.push(`${doc}  static const Cubic ${name} = Cubic(${v.map((n) => dbl(n, 3)).join(', ')});`);
          break;
        case 'shadow': {
          const layers = Array.isArray(v) ? v : [v];
          const inset = layers.filter((l) => l.inset);
          if (inset.length) {
            const l = inset[0];
            const c = parseColor(l.color);
            out.push(
              `${doc}  /// CSS \`inset\` shadow — Flutter has no inset BoxShadow; draw it with` +
                ` \`Border.all(color: ${name}Color, width: ${name}Width)\`.`,
            );
            out.push(`  static const Color ${name}Color = Color(0x${argbHex(c)});`);
            out.push(`  static const double ${name}Width = ${fmt(px(l.spread ?? '1px'))};`);
          } else {
            out.push(
              `${doc}  static const List<BoxShadow> ${name} = [${layers.map(dartShadowLayer).join(', ')}];`,
            );
          }
          break;
        }
        case 'typography': {
          const size = px(v.fontSize);
          const lh = px(v.lineHeight);
          const ls = parseUnit(v.letterSpacing);
          const spacingPx = ls.u === 'em' ? ls.n * size : ls.n;
          const args = [
            `fontSize: ${fmt(size)}`,
            `height: ${dbl(lh / size)}`,
            `fontWeight: ${DART_WEIGHT(v.fontWeight)}`,
            `letterSpacing: ${fmt(spacingPx)}`,
          ];
          if (v.fontVariantNumeric === 'tabular-nums') {
            args.push('fontFeatures: [FontFeature.tabularFigures()]');
          }
          const notes = [];
          if (v.textTransform) notes.push(`text-transform: ${v.textTransform} (apply with toUpperCase())`);
          if (notes.length) out.push(`  /// ${notes.join('; ')}`);
          out.push(`${doc}  static const TextStyle ${name} = TextStyle(${args.join(', ')});`);
          break;
        }
        case 'string':
          out.push(`  // ${displayPath(t)} (CSS gradient, not representable as a const): ${v}`);
          break;
        default:
          throw new Error(`dart: unhandled $type "${t.$type}" at ${displayPath(t)}`);
      }
    }
  }
  out.push('}', '');
  return out.join('\n');
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 5. dist/swift/TPTokens.swift                                               */
/* ────────────────────────────────────────────────────────────────────────── */

function swiftColor(v) {
  const c = parseColor(v);
  const ch = (n) => dbl(n / 255, 4);
  return `UIColor(red: ${ch(c.r)}, green: ${ch(c.g)}, blue: ${ch(c.b)}, alpha: ${dbl(c.a, 3)})`;
}

const SWIFT_WEIGHT = {
  100: '.ultraLight',
  200: '.thin',
  300: '.light',
  400: '.regular',
  500: '.medium',
  600: '.semibold',
  700: '.bold',
  800: '.heavy',
  900: '.black',
};

function swiftWeight(w) {
  const s = SWIFT_WEIGHT[w];
  if (!s) throw new Error(`swift: no UIFont.Weight for ${w}`);
  return s;
}

function swiftShadowLayer(l) {
  const c = parseColor(l.color);
  const opaque = { ...c, a: 1 };
  const args = [
    `color: ${swiftColor(`#${argbHex(opaque).slice(2)}`)}`,
    `opacity: ${dbl(c.a, 3)}`,
    `offset: CGSize(width: ${fmt(px(l.offsetX))}, height: ${fmt(px(l.offsetY))})`,
    `radius: ${fmt(px(l.blur))}`,
  ];
  const spread = px(l.spread ?? '0px');
  if (spread !== 0) args.push(`spread: ${fmt(spread)}`);
  if (l.inset) args.push('inset: true');
  return `TPShadow(${args.join(', ')})`;
}

function formatSwift({ dictionary }) {
  const out = [
    `// ${HEADER}`,
    '',
    'import UIKit',
    '',
    '/// A typography role: point size, line height, weight and tracking (points).',
    'public struct TPTextStyle {',
    '    public let size: CGFloat',
    '    public let lineHeight: CGFloat',
    '    public let weight: UIFont.Weight',
    '    public let tracking: CGFloat',
    '',
    '    public init(size: CGFloat, lineHeight: CGFloat, weight: UIFont.Weight, tracking: CGFloat) {',
    '        self.size = size',
    '        self.lineHeight = lineHeight',
    '        self.weight = weight',
    '        self.tracking = tracking',
    '    }',
    '',
    '    /// System font (SF Pro) at this role\'s size and weight.',
    '    public var font: UIFont { UIFont.systemFont(ofSize: size, weight: weight) }',
    '}',
    '',
    '/// One shadow layer. `radius` is the CSS blur radius in points;',
    '/// for `CALayer.shadowRadius` use `layerRadius` (blur ÷ 2).',
    'public struct TPShadow {',
    '    public let color: UIColor',
    '    public let opacity: Float',
    '    public let offset: CGSize',
    '    public let radius: CGFloat',
    '    public let spread: CGFloat',
    '    public let inset: Bool',
    '',
    '    public init(color: UIColor, opacity: Float, offset: CGSize, radius: CGFloat, spread: CGFloat = 0, inset: Bool = false) {',
    '        self.color = color',
    '        self.opacity = opacity',
    '        self.offset = offset',
    '        self.radius = radius',
    '        self.spread = spread',
    '        self.inset = inset',
    '    }',
    '',
    '    public var layerRadius: CGFloat { radius / 2 }',
    '}',
    '',
    '/// TP VPN design tokens (Light mode only).',
    '/// Naming: token path `color.bg.canvas` → `TPTokens.colorBgCanvas`.',
    'public enum TPTokens {',
  ];
  let first = true;
  for (const [group, tokens] of sectionsOf(dictionary.allTokens)) {
    if (!first) out.push('');
    first = false;
    out.push(`    // MARK: - ${group}`);
    for (const t of tokens) {
      const name = camel(t.path);
      const doc = t.$description ? `    /// ${t.$description}\n` : '';
      const v = t.$value;
      switch (t.$type) {
        case 'color':
          out.push(`${doc}    public static let ${name} = ${swiftColor(v)}`);
          break;
        case 'dimension': {
          const { n, u } = parseUnit(v);
          if (u === 'em') {
            out.push(`${doc}    /// Unit: em (multiply by the font size).\n    public static let ${name}: CGFloat = ${dbl(n)}`);
          } else {
            out.push(`${doc}    public static let ${name}: CGFloat = ${fmt(n)}`);
          }
          break;
        }
        case 'number': {
          const isInt = Number.isInteger(v) && isGroup(t, 'z-index', 'grid');
          out.push(`${doc}    public static let ${name}: ${isInt ? 'Int' : 'CGFloat'} = ${isInt ? v : dbl(v)}`);
          break;
        }
        case 'fontWeight':
          out.push(`${doc}    public static let ${name}: UIFont.Weight = ${swiftWeight(v)}`);
          break;
        case 'fontFamily':
          out.push(`${doc}    public static let ${name}: [String] = [${v.map(dq).join(', ')}]`);
          break;
        case 'duration':
          out.push(`${doc}    public static let ${name}: TimeInterval = ${dbl(ms(v) / 1000, 3)}`);
          break;
        case 'cubicBezier':
          out.push(`${doc}    public static let ${name}: [CGFloat] = [${v.map((n) => dbl(n, 3)).join(', ')}]`);
          break;
        case 'shadow': {
          const layers = Array.isArray(v) ? v : [v];
          out.push(`${doc}    public static let ${name}: [TPShadow] = [${layers.map(swiftShadowLayer).join(', ')}]`);
          break;
        }
        case 'typography': {
          const size = px(v.fontSize);
          const lh = px(v.lineHeight);
          const ls = parseUnit(v.letterSpacing);
          const tracking = ls.u === 'em' ? ls.n * size : ls.n;
          const notes = [];
          if (v.textTransform) notes.push(`text-transform: ${v.textTransform}`);
          if (v.fontVariantNumeric) notes.push(`font-variant-numeric: ${v.fontVariantNumeric} (UIFontDescriptor tabular figures)`);
          if (notes.length) out.push(`    /// ${notes.join('; ')}`);
          out.push(
            `${doc}    public static let ${name} = TPTextStyle(size: ${fmt(size)}, lineHeight: ${fmt(lh)}, weight: ${swiftWeight(v.fontWeight)}, tracking: ${fmt(tracking)})`,
          );
          break;
        }
        case 'string':
          out.push(`    // ${displayPath(t)} (CSS gradient — build a CAGradientLayer): ${v}`);
          break;
        default:
          throw new Error(`swift: unhandled $type "${t.$type}" at ${displayPath(t)}`);
      }
    }
  }
  out.push('}', '');
  return out.join('\n');
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 6. dist/kotlin/TpTokens.kt + dist/android/values/*.xml                     */
/* ────────────────────────────────────────────────────────────────────────── */

function kotlinColor(v) {
  const c = parseColor(v);
  return `Color(0x${argbHex(c)})`;
}

const isSpUnit = (t) => t.path[0] === 'font' && (t.path[1] === 'size' || t.path[1] === 'line-height');

function kotlinShadowLayer(l) {
  const args = [
    `color = ${kotlinColor(l.color)}`,
    `offsetX = ${fmt(px(l.offsetX))}.dp`,
    `offsetY = ${fmt(px(l.offsetY))}.dp`,
    `blur = ${fmt(px(l.blur))}.dp`,
  ];
  const spread = px(l.spread ?? '0px');
  if (spread !== 0) args.push(`spread = ${fmt(spread)}.dp`);
  if (l.inset) args.push('inset = true');
  return `TpShadow(${args.join(', ')})`;
}

const kf = (n, d = 4) => `${dbl(n, d)}f`;

function formatKotlin({ dictionary }) {
  const out = [
    `// ${HEADER}`,
    'package com.tpvpn.design',
    '',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.compose.ui.text.TextStyle',
    'import androidx.compose.ui.text.font.FontWeight',
    'import androidx.compose.ui.unit.Dp',
    'import androidx.compose.ui.unit.TextUnit',
    'import androidx.compose.ui.unit.dp',
    'import androidx.compose.ui.unit.em',
    'import androidx.compose.ui.unit.sp',
    '',
    '/** A typography role. `letterSpacing` is in em (fraction of the font size). */',
    'data class TpTextStyle(',
    '    val size: TextUnit,',
    '    val lineHeight: TextUnit,',
    '    val weight: Int,',
    '    val letterSpacing: Float,',
    ') {',
    '    fun toTextStyle(): TextStyle = TextStyle(',
    '        fontSize = size,',
    '        lineHeight = lineHeight,',
    '        fontWeight = FontWeight(weight),',
    '        letterSpacing = letterSpacing.em,',
    '    )',
    '}',
    '',
    '/** One shadow layer (CSS box-shadow semantics; `color` carries the alpha). */',
    'data class TpShadow(',
    '    val color: Color,',
    '    val offsetX: Dp,',
    '    val offsetY: Dp,',
    '    val blur: Dp,',
    '    val spread: Dp = 0.dp,',
    '    val inset: Boolean = false,',
    ')',
    '',
    '/**',
    ' * TP VPN design tokens (Light mode only).',
    ' * Naming: token path `color.bg.canvas` → `TpTokens.colorBgCanvas`.',
    ' */',
    'object TpTokens {',
  ];
  let first = true;
  for (const [group, tokens] of sectionsOf(dictionary.allTokens)) {
    if (!first) out.push('');
    first = false;
    out.push(`    // ── ${group} ${'─'.repeat(Math.max(2, 60 - group.length))}`);
    for (const t of tokens) {
      const name = camel(t.path);
      const doc = t.$description ? `    /** ${t.$description} */\n` : '';
      const v = t.$value;
      switch (t.$type) {
        case 'color':
          out.push(`${doc}    val ${name} = ${kotlinColor(v)}`);
          break;
        case 'dimension': {
          const { n, u } = parseUnit(v);
          if (u === 'em') {
            out.push(`${doc}    /** Unit: em (use \`.em\`). */\n    val ${name} = ${kf(n)}`);
          } else {
            out.push(`${doc}    val ${name} = ${fmt(n)}.${isSpUnit(t) ? 'sp' : 'dp'}`);
          }
          break;
        }
        case 'number': {
          const isInt = Number.isInteger(v) && isGroup(t, 'z-index', 'grid');
          out.push(`${doc}    val ${name} = ${isInt ? v : kf(v)}`);
          break;
        }
        case 'fontWeight':
          out.push(`${doc}    val ${name} = ${v}`);
          break;
        case 'fontFamily':
          out.push(`${doc}    val ${name} = listOf(${v.map(dq).join(', ')})`);
          break;
        case 'duration':
          out.push(`${doc}    /** Milliseconds. */\n    val ${name} = ${fmt(ms(v))}`);
          break;
        case 'cubicBezier':
          out.push(
            `${doc}    /** Control points (a, b, c, d) — \`CubicBezierEasing(a, b, c, d)\`. */\n    val ${name} = floatArrayOf(${v.map((n) => kf(n, 3)).join(', ')})`,
          );
          break;
        case 'shadow': {
          const layers = Array.isArray(v) ? v : [v];
          const body = layers.length ? `listOf(${layers.map(kotlinShadowLayer).join(', ')})` : 'emptyList<TpShadow>()';
          out.push(`${doc}    val ${name} = ${body}`);
          break;
        }
        case 'typography': {
          const size = px(v.fontSize);
          const lh = px(v.lineHeight);
          const ls = parseUnit(v.letterSpacing);
          const em = ls.u === 'em' ? ls.n : ls.n / size;
          const notes = [];
          if (v.textTransform) notes.push(`text-transform: ${v.textTransform}`);
          if (v.fontVariantNumeric) notes.push(`font-variant-numeric: ${v.fontVariantNumeric} (FontFeatureSettings "tnum")`);
          if (notes.length) out.push(`    /** ${notes.join('; ')} */`);
          out.push(
            `${doc}    val ${name} = TpTextStyle(size = ${fmt(size)}.sp, lineHeight = ${fmt(lh)}.sp, weight = ${v.fontWeight}, letterSpacing = ${kf(em)})`,
          );
          break;
        }
        case 'string':
          out.push(`    // ${displayPath(t)} (CSS gradient — use Brush.linearGradient): ${v}`);
          break;
        default:
          throw new Error(`kotlin: unhandled $type "${t.$type}" at ${displayPath(t)}`);
      }
    }
  }
  out.push('}', '');
  return out.join('\n');
}

const xmlEscape = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function formatAndroidColors({ dictionary }) {
  const out = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${HEADER} -->`, '<resources>'];
  for (const t of dictionary.allTokens) {
    if (t.$type !== 'color') continue;
    const comment = t.$description ? ` <!-- ${xmlEscape(t.$description)} -->` : '';
    out.push(`    <color name="tp_${snake(t.path)}">#${argbHex(parseColor(t.$value))}</color>${comment}`);
  }
  out.push('</resources>', '');
  return out.join('\n');
}

function formatAndroidDimens({ dictionary }) {
  const out = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${HEADER} -->`, '<resources>'];
  for (const t of dictionary.allTokens) {
    if (t.$type !== 'dimension') continue;
    const { n, u } = parseUnit(t.$value);
    const name = `tp_${snake(t.path)}`;
    const comment = t.$description ? ` <!-- ${xmlEscape(t.$description)} -->` : '';
    if (u === 'em') {
      out.push(`    <item name="${name}" format="float" type="dimen">${fmt(n)}</item> <!-- em -->`);
    } else {
      out.push(`    <dimen name="${name}">${fmt(n)}${isSpUnit(t) ? 'sp' : 'dp'}</dimen>${comment}`);
    }
  }
  out.push('</resources>', '');
  return out.join('\n');
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 7. dist/figma/tokens.json (Tokens Studio single-file)                      */
/* ────────────────────────────────────────────────────────────────────────── */

/** DTCG → Tokens Studio type, refined by path so Figma variable scopes are right. */
function figmaType(t) {
  const [g, s] = t.path;
  switch (t.$type) {
    case 'color':
      return 'color';
    case 'string':
      return g === 'gradient' ? 'color' : 'text';
    case 'dimension': {
      if (g === 'font' && s === 'size') return 'fontSizes';
      if (g === 'font' && s === 'line-height') return 'lineHeights';
      if (g === 'font' && s === 'letter-spacing') return 'letterSpacing';
      if (g === 'radius') return 'borderRadius';
      if (g === 'space') return 'spacing';
      if (g === 'border-width') return 'borderWidth';
      if (g === 'size') return 'sizing';
      if (isComponent(t)) {
        // Component-level dimensions: infer the Figma scope from the property name.
        const prop = t.path.slice(1).join('-');
        if (/radius/.test(prop)) return 'borderRadius';
        if (/padding|gap/.test(prop)) return 'spacing';
        if (/width$/.test(prop) && /ring|border/.test(prop)) return 'borderWidth';
        if (/height|width|size|thumb/.test(prop)) return 'sizing';
      }
      return 'dimension';
    }
    case 'fontFamily':
      return 'fontFamilies';
    case 'fontWeight':
      return 'fontWeights';
    case 'number':
      return g === 'opacity' ? 'opacity' : 'number';
    case 'duration':
    case 'cubicBezier':
      return 'other';
    case 'shadow':
      return 'boxShadow';
    case 'typography':
      return 'typography';
    default:
      throw new Error(`figma: unhandled $type "${t.$type}" at ${displayPath(t)}`);
  }
}

/** em letter-spacing → Figma percentage ("-0.02em" → "-2%"); references pass through. */
function figmaLetterSpacing(v) {
  if (typeof v !== 'string' || v.startsWith('{')) return v;
  const { n, u } = parseUnit(v);
  return u === 'em' ? `${fmt(n * 100)}%` : v;
}

function figmaShadowLayer(l) {
  return {
    x: shadowLen(l.offsetX).replace(/^0$/, '0'),
    y: shadowLen(l.offsetY),
    blur: shadowLen(l.blur),
    spread: shadowLen(l.spread ?? '0px'),
    color: cssColor(l.color),
    type: l.inset ? 'innerShadow' : 'dropShadow',
  };
}

function figmaValue(t) {
  const original = t.original.$value;
  const type = figmaType(t);
  const isRef = (x) => typeof x === 'string' && /^\{[^}]+\}$/.test(x.trim());
  switch (t.$type) {
    case 'fontFamily':
      return Array.isArray(original) ? original.join(', ') : original;
    case 'cubicBezier':
      return isRef(original) ? original : cssBezier(original);
    case 'duration':
      return original;
    case 'dimension':
      return type === 'letterSpacing' ? figmaLetterSpacing(original) : original;
    case 'shadow': {
      if (isRef(original)) return original;
      const layers = Array.isArray(original) ? original : [original];
      if (layers.length === 0) return 'none';
      const mapped = layers.map(figmaShadowLayer);
      return mapped.length === 1 ? mapped[0] : mapped;
    }
    case 'typography': {
      const o = original;
      const val = {
        fontFamily: o.fontFamily,
        fontWeight: o.fontWeight,
        fontSize: o.fontSize,
        lineHeight: o.lineHeight,
        letterSpacing: figmaLetterSpacing(o.letterSpacing),
      };
      if (o.textTransform) val.textCase = o.textTransform;
      return val;
    }
    default:
      return original;
  }
}

function formatFigma({ dictionary }) {
  const global = {};
  for (const t of dictionary.allTokens) {
    let node = global;
    for (const seg of t.path.slice(0, -1)) {
      node[seg] ??= {};
      node = node[seg];
    }
    const layers = t.$type === 'shadow' ? (Array.isArray(t.$value) ? t.$value : [t.$value]) : null;
    const leaf = {
      value: figmaValue(t),
      type: layers && layers.length === 0 ? 'other' : figmaType(t),
    };
    const desc = [];
    if (t.$description) desc.push(t.$description);
    if (t.$type === 'typography' && t.$value.fontVariantNumeric) desc.push(`font-variant-numeric: ${t.$value.fontVariantNumeric}`);
    if (desc.length) leaf.description = desc.join(' · ');
    node[t.path.at(-1)] = leaf;
  }
  const doc = { global, $themes: [], $metadata: { tokenSetOrder: ['global'] } };
  return JSON.stringify(doc, null, 2) + '\n';
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 8. dist/README.md                                                          */
/* ────────────────────────────────────────────────────────────────────────── */

function formatReadme({ dictionary }) {
  const n = dictionary.allTokens.length;
  return `# @tpvpn/tokens — build output

${HEADER}. Source of truth: \`packages/tokens/src/**/*.json\` (W3C DTCG) → \`node build.mjs\`.
${n} tokens, Light mode only. Naming: \`color.bg.canvas\` → CSS \`--tp-color-bg-canvas\` → Tailwind \`--color-bg-canvas\` → Dart/Swift/Kotlin \`colorBgCanvas\`.

| File | Platform | How to consume |
|---|---|---|
| \`css/tokens.css\` | Any web | \`@import '@tpvpn/tokens/css';\` — every token as \`--tp-*\` on \`:root\`. Typography roles are split into \`-font-family/-font-size/-line-height/-font-weight/-letter-spacing\`. |
| \`tailwind/theme.css\` | Tailwind CSS v4 | \`@import 'tailwindcss'; @import '@tpvpn/tokens/tailwind';\` — gives \`bg-bg-canvas\`, \`text-fg-primary\`, \`bg-action-primary-bg\`, \`text-body\`, \`rounded-lg\`, \`shadow-level-2\`, \`ease-standard\`, \`h-control-md\`, \`max-w-content\`. Gradients, z-index, opacity and component tokens sit in a plain \`:root\` block as \`--gradient-*\`, \`--z-index-*\`, \`--opacity-*\`, \`--tp-*\`. |
| \`json/tokens.json\` | Any (nested) | \`import tokens from '@tpvpn/tokens'\` — resolved tree keeping \`$type\`/\`$description\`. |
| \`json/tokens.flat.json\` | Any (flat) | \`import flat from '@tpvpn/tokens/flat'\` — \`flat['color.bg.canvas'] = { value, type, description, original }\`; \`original\` is the source reference (e.g. \`{color.slate.25}\`) or raw value. |
| \`dart/tp_tokens.dart\` | Flutter | Copy into \`lib/core/theme/\` (or add the package path). \`TpTokens.colorBgCanvas\`, \`TpTokens.radiusMd\`, \`TpTokens.typographyBody\` (\`TextStyle\`), \`TpTokens.elevationLevel2\` (\`List<BoxShadow>\`), \`TpTokens.durationBase\`, \`TpTokens.easingStandard\` (\`Cubic\`). Gradients are listed as comments — build them with \`LinearGradient\`. |
| \`swift/TPTokens.swift\` | iOS / UIKit | Add the file to your target. \`TPTokens.colorBgCanvas\` (\`UIColor\`), \`TPTokens.radiusMd\` (\`CGFloat\`), \`TPTokens.typographyBody\` (\`TPTextStyle\` → \`.font\`), \`TPTokens.elevationLevel2\` (\`[TPShadow]\`, use \`layerRadius\` for \`CALayer.shadowRadius\`), \`TPTokens.durationBase\` (seconds), \`TPTokens.easingStandard\` (control points). |
| \`kotlin/TpTokens.kt\` | Android / Jetpack Compose | Drop into \`com.tpvpn.design\`. \`TpTokens.colorBgCanvas\` (\`Color\`), \`TpTokens.radiusMd\` (\`Dp\`), \`TpTokens.typographyBody.toTextStyle()\`, \`TpTokens.elevationLevel2\` (\`List<TpShadow>\`), \`TpTokens.durationBase\` (ms), \`TpTokens.easingStandard\` → \`CubicBezierEasing(a, b, c, d)\`. |
| \`android/values/colors.xml\`, \`dimens.xml\` | Android Views / XML | Copy into \`res/values/\`. \`@color/tp_color_bg_canvas\` (ARGB), \`@dimen/tp_radius_md\` (dp), font sizes and line heights in sp, em letter-spacing as float items. |
| \`figma/tokens.json\` | Figma (Tokens Studio) | Tokens Studio → Settings → Sync → *Local file / JSON* → import this file (single set \`global\`). References such as \`{color.blue.500}\` are resolved by the plugin; then *Export to Figma → Variables* to create Figma Variables and styles. |

Rebuild after editing any source file: \`pnpm --filter @tpvpn/tokens build\`. Never edit files in \`dist/\` by hand.
`;
}

/* ────────────────────────────────────────────────────────────────────────── */
/* Style Dictionary wiring                                                    */
/* ────────────────────────────────────────────────────────────────────────── */

const FORMATS = {
  'tp/css': formatCss,
  'tp/tailwind': formatTailwind,
  'tp/json-nested': formatJsonNested,
  'tp/json-flat': formatJsonFlat,
  'tp/dart': formatDart,
  'tp/swift': formatSwift,
  'tp/kotlin': formatKotlin,
  'tp/android-colors': formatAndroidColors,
  'tp/android-dimens': formatAndroidDimens,
  'tp/figma': formatFigma,
  'tp/readme': formatReadme,
};
for (const [name, format] of Object.entries(FORMATS)) StyleDictionary.registerFormat({ name, format });

const platform = (dir, files) => ({
  transforms: ['name/kebab'],
  buildPath: `${path.join(DIST, dir)}/`,
  files: files.map(([destination, format]) => ({ destination, format })),
});

const OUTPUTS = {
  css: platform('css', [['tokens.css', 'tp/css']]),
  tailwind: platform('tailwind', [['theme.css', 'tp/tailwind']]),
  json: platform('json', [
    ['tokens.json', 'tp/json-nested'],
    ['tokens.flat.json', 'tp/json-flat'],
  ]),
  dart: platform('dart', [['tp_tokens.dart', 'tp/dart']]),
  swift: platform('swift', [['TPTokens.swift', 'tp/swift']]),
  kotlin: platform('kotlin', [['TpTokens.kt', 'tp/kotlin']]),
  android: platform('android/values', [
    ['colors.xml', 'tp/android-colors'],
    ['dimens.xml', 'tp/android-dimens'],
  ]),
  figma: platform('figma', [['tokens.json', 'tp/figma']]),
  readme: platform('', [['README.md', 'tp/readme']]),
};

async function build() {
  await Promise.all(Object.values(OUTPUTS).map((p) => mkdir(p.buildPath, { recursive: true })));

  const sd = new StyleDictionary({
    usesDtcg: true,
    source: SOURCE,
    platforms: OUTPUTS,
    log: { verbosity: 'default', warnings: 'error' },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();
  return sd;
}

/* ────────────────────────────────────────────────────────────────────────── */
/* Verification                                                               */
/* ────────────────────────────────────────────────────────────────────────── */

async function verify(sd) {
  const read = (rel) => readFile(path.join(DIST, rel), 'utf8');
  const problems = [];
  const expect = (cond, msg) => {
    if (!cond) problems.push(msg);
  };

  const outputs = [
    'css/tokens.css',
    'tailwind/theme.css',
    'json/tokens.json',
    'json/tokens.flat.json',
    'dart/tp_tokens.dart',
    'swift/TPTokens.swift',
    'kotlin/TpTokens.kt',
    'android/values/colors.xml',
    'android/values/dimens.xml',
    'figma/tokens.json',
    'README.md',
  ];
  const contents = Object.fromEntries(await Promise.all(outputs.map(async (f) => [f, await read(f)])));

  // No leaked JS artefacts anywhere
  for (const [file, text] of Object.entries(contents)) {
    for (const bad of ['undefined', '[object Object]', 'NaN', 'null,']) {
      expect(!text.includes(bad), `${file} contains "${bad}"`);
    }
    expect(text.length > 0, `${file} is empty`);
  }

  // Key Tailwind contract variables
  const theme = contents['tailwind/theme.css'];
  for (const needle of [
    '--color-action-primary-bg: #046BEF;',
    '--color-bg-canvas: #FAFBFF;',
    '--color-fg-primary: #0F172A;',
    '--text-body: 0.875rem;',
    '--text-body--line-height: 1.375rem;',
    '--shadow-level-1: 0 1px 2px rgba(15, 23, 42, 0.06), 0 1px 3px rgba(15, 23, 42, 0.04);',
    '--inset-shadow-hairline: inset 0 0 0 1px rgba(15, 23, 42, 0.08);',
    '--ease-standard: cubic-bezier(0.2, 0, 0, 1);',
    '--duration-base: 200ms;',
    '--radius-md: 12px;',
    '--spacing: 0.25rem;',
    '--spacing-control-md: 44px;',
    '--spacing-connection-mobile: 128px;',
    '--breakpoint-md: 768px;',
    '--container-content: 1200px;',
    '--font-weight-bold: 700;',
    '--tracking-tight: -0.02em;',
    '--gradient-primary: linear-gradient(135deg, #1677FF 0%, #4096FF 100%);',
    '--z-index-modal: 1100;',
    '--tp-button-primary-bg: #046BEF;',
    '--tp-connection-button-connected-shadow: 0 20px 60px rgba(22, 119, 255, 0.45);',
  ]) {
    expect(theme.includes(needle), `theme.css missing "${needle}"`);
  }
  expect(theme.startsWith(`/* ${HEADER} */`), 'theme.css missing header comment');
  expect(/^@theme \{[\s\S]*?\n\}\n\n:root \{[\s\S]*?\n\}\n$/m.test(theme), 'theme.css block structure unexpected');

  // tokens.css
  const css = contents['css/tokens.css'];
  for (const needle of [
    '--tp-color-bg-canvas: #FAFBFF;',
    '--tp-typography-body-font-size: 14px;',
    '--tp-typography-body-line-height: 22px;',
    '--tp-typography-overline-text-transform: uppercase;',
    '--tp-typography-numeric-lg-font-variant-numeric: tabular-nums;',
    '--tp-elevation-level-0: none;',
    '--tp-easing-spring: cubic-bezier(0.34, 1.56, 0.64, 1);',
    "--tp-font-family-sans: 'Inter Variable', Inter, -apple-system, BlinkMacSystemFont, 'SF Pro Text'",
  ]) {
    expect(css.includes(needle), `tokens.css missing "${needle}"`);
  }

  // JSON outputs parse and agree with the dictionary
  const flat = JSON.parse(contents['json/tokens.flat.json']);
  const nested = JSON.parse(contents['json/tokens.json']);
  const figma = JSON.parse(contents['figma/tokens.json']);
  const total = sd.allTokens.length;
  expect(Object.keys(flat).length === total, `tokens.flat.json has ${Object.keys(flat).length} entries, expected ${total}`);
  expect(flat['color.bg.canvas']?.value === '#FAFBFF', 'flat color.bg.canvas value');
  expect(flat['color.bg.canvas']?.original === '{color.slate.25}', 'flat color.bg.canvas original reference');
  expect(flat['color.blue.500']?.original === '#1677FF', 'flat color.blue.500 original raw value');
  expect(nested.color?.bg?.canvas?.$value === '#FAFBFF', 'nested color.bg.canvas');
  expect(nested.typography?.body?.$value?.fontSize === '14px', 'nested typography.body resolved');
  expect(figma.global?.color?.bg?.canvas?.value === '{color.slate.25}', 'figma keeps references');
  expect(figma.global?.typography?.body?.type === 'typography', 'figma typography type');
  expect(figma.global?.elevation?.['level-1']?.type === 'boxShadow', 'figma boxShadow type');
  expect(Array.isArray(figma.$themes) && figma.$metadata?.tokenSetOrder?.[0] === 'global', 'figma metadata');

  // Native files — spot checks on the exact literals the contract promises
  const dart = contents['dart/tp_tokens.dart'];
  for (const needle of [
    "import 'package:flutter/material.dart';",
    'abstract final class TpTokens {',
    'static const Color colorBgCanvas = Color(0xFFFAFBFF);',
    'static const double radiusMd = 12;',
    'static const FontWeight fontWeightBold = FontWeight.w700;',
    'static const TextStyle typographyBody = TextStyle(fontSize: 14, height: 1.5714, fontWeight: FontWeight.w400, letterSpacing: 0);',
    'static const List<BoxShadow> elevationLevel1 = [BoxShadow(color: Color(0x0F0F172A), offset: Offset(0, 1), blurRadius: 2), BoxShadow(color: Color(0x0A0F172A), offset: Offset(0, 1), blurRadius: 3)];',
    'static const Duration durationBase = Duration(milliseconds: 200);',
    'static const Cubic easingStandard = Cubic(0.2, 0.0, 0.0, 1.0);',
    'static const Color colorAlphaInk4 = Color.fromRGBO(15, 23, 42, 0.04);',
  ]) {
    expect(dart.includes(needle), `tp_tokens.dart missing "${needle}"`);
  }
  const swift = contents['swift/TPTokens.swift'];
  for (const needle of [
    'import UIKit',
    'public enum TPTokens {',
    'public static let radiusMd: CGFloat = 12',
    'public static let fontWeightBold: UIFont.Weight = .bold',
    'public static let typographyBody = TPTextStyle(size: 14, lineHeight: 22, weight: .regular, tracking: 0)',
    'public static let durationBase: TimeInterval = 0.2',
    'public static let easingStandard: [CGFloat] = [0.2, 0.0, 0.0, 1.0]',
  ]) {
    expect(swift.includes(needle), `TPTokens.swift missing "${needle}"`);
  }
  const kt = contents['kotlin/TpTokens.kt'];
  for (const needle of [
    'package com.tpvpn.design',
    'object TpTokens {',
    'val colorBgCanvas = Color(0xFFFAFBFF)',
    'val radiusMd = 12.dp',
    'val fontWeightBold = 700',
    'val typographyBody = TpTextStyle(size = 14.sp, lineHeight = 22.sp, weight = 400, letterSpacing = 0.0f)',
    'val fontSize14 = 14.sp',
  ]) {
    expect(kt.includes(needle), `TpTokens.kt missing "${needle}"`);
  }
  expect(contents['android/values/colors.xml'].includes('<color name="tp_color_bg_canvas">#FFFAFBFF</color>'), 'colors.xml canvas');
  expect(contents['android/values/dimens.xml'].includes('<dimen name="tp_radius_md">12dp</dimen>'), 'dimens.xml radius');
  expect(contents['android/values/dimens.xml'].includes('<dimen name="tp_font_size_14">14sp</dimen>'), 'dimens.xml sp');

  // Balanced braces in generated source files
  for (const f of ['dart/tp_tokens.dart', 'swift/TPTokens.swift', 'kotlin/TpTokens.kt']) {
    const text = contents[f];
    const open = (text.match(/\{/g) || []).length;
    const close = (text.match(/\}/g) || []).length;
    expect(open === close, `${f} has unbalanced braces (${open} vs ${close})`);
  }

  if (problems.length) {
    console.error('\n✖ Verification failed:');
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }

  // Summary
  const byType = {};
  for (const t of sd.allTokens) byType[t.$type] = (byType[t.$type] ?? 0) + 1;
  const themeVars = (theme.match(/^\s+--[a-z0-9-]+:/gm) || []).length;
  const cssVars = (css.match(/^\s+--tp-[a-z0-9-]+:/gm) || []).length;
  console.log('\n✔ @tpvpn/tokens built and verified');
  console.log(`  tokens: ${total}  (${Object.entries(byType).map(([k, v]) => `${k} ${v}`).join(', ')})`);
  console.log(`  css/tokens.css: ${cssVars} variables · tailwind/theme.css: ${themeVars} variables`);
  console.log(`  outputs: ${outputs.length} files in ${path.relative(ROOT, DIST)}/`);
}

const sd = await build();
await verify(sd);
